server:
  port: 8088

spring:
  application:
    name: api-driver
  cloud:
    nacos:
      discovery:
        server-addr: http://101.201.154.144:8848
  redis:
    host: 101.201.154.144
    port: 6379
    password: Ssl@134679
    database: 0

management:
  endpoint:
    web:
      exposure:
        include: '*'
