server:
  port: 8085

spring:
  profiles:
    active: default
  application:
    name: service-map
  cloud:
    nacos:
      discovery:
        server-addr: http://101.201.154.144:8848

management:
  endpoint:
    web:
      exposure:
        include: '*'

amap:
  key: f7db1c44b0132b46fb2a78cc0f6e25be